### ISSUE TITLE
📝 폴더 정리하여 폴더트리 구조로 정리하기

### ISSUE THREAD

**Issue by Hyunja27** [KKWANH/webserv#33]
├── tester
└──webserv
     ├── errorHandler
     ├── setting
      │         ├── config
      │         ├── MIME
      │         └── statusCode
     ├── HTTPMessageController
      │         ├── HTTPMessage
      │         ├── requestMessage
      │         └── responseMessage
     ├── parsingController
      │         ├── configParsing
      │         ├── MIMEParsing
      │         └── statusCodeParsing
     ├── serverProcessController
      │         └── serverProcess
     ├── fileController
     ├── CGIConsroller
     ├── main.cpp
    └── makefile

**Comment by Hyunja27** [comment]
여러분.
트리가 거지같아서 놀라셨죠?

진정하고 여길 들어가보세요.

마음이 편-안 해집니다.
https://hushed-sumac-cc4.notion.site/5f4108df3064425e8b95c62097d6c055

**Comment by HyeonsikBae** [comment]
#37
